#!/usr/bin/env python3

import argparse
from collections import namedtuple
import xml.etree.ElementTree as ET
import json
import sys

StructType = namedtuple('StructType', ['extends', 'member_types'])
EnumType = namedtuple('EnumType', ['extensions'])

def traverse_active_struct_type(active_types, t, mapping):
    if t not in mapping:
        return
    if t in active_types:
        return
    active_types.add(t)
    for m in mapping[t].member_types:
        traverse_active_struct_type(active_types, m, mapping)

def traverse_active_struct_types(base_types, mapping):
    active_types = set()
    for t in base_types:
        traverse_active_struct_type(active_types, t, mapping)
    return active_types

def struct_extends_any(active_types, t, mappings):
    if t not in mappings:
        return False
    for e in mappings[t].extends:
        if e in active_types or struct_extends_any(active_types, e, mappings):
            return True
    return False

def find_extending_structs(active_types, mappings):
    extending_structs = set()
    for m in mappings.keys():
        if struct_extends_any(active_types, m, mappings):
            for memb in traverse_active_struct_types([m], mappings):
                extending_structs.add(memb)
    return extending_structs

def find_active_enum_types(active_types, extending_types, mappings, enum_types, bitmask_reqs):
    active_enum_types = set()

    for t in active_types:
        for m in mappings[t].member_types:
            if m in bitmask_reqs:
                active_enum_types.add(bitmask_reqs[m])
            elif m in enum_types:
                active_enum_types.add(m)

    for t in extending_types:
        for m in mappings[t].member_types:
            if m in bitmask_reqs:
                active_enum_types.add(bitmask_reqs[m])
            elif m in enum_types:
                active_enum_types.add(m)

    return active_enum_types

def main():
    parser = argparse.ArgumentParser(description = 'Script for extracting what needs to be sifted through w.r.t. PDF2.')
    parser.add_argument('--xml', help = 'Path to Vulkan registry XML.')
    args = parser.parse_args()
    if not args.xml:
        sys.stderr.write('Need XML.\n')
        sys.exit(1)

    tree = ET.parse(args.xml)
    root = tree.getroot()

    struct_types = {}
    enum_types = {}
    bitmask_requirements = {}
    type_aliases = {}
    feature_structs = {}

    for t in root.find('types').iter('type'):
        if 'alias' in t.attrib:
            type_aliases[t.attrib['name']] = t.attrib['alias']

    pNextLUT = []

    for t in root.find('types').iter('type'):
        if 'category' not in t.attrib:
            continue
        category = t.attrib['category']
        if category == 'struct':
            name = t.attrib['name']
            member_types = []
            extended_types = set()
            extends = set()
            if 'structextends' in t.attrib:
                extends = t.attrib['structextends'].split(',')
                extends = set([type_aliases.get(x, x) for x in extends])
                if ('VkPhysicalDeviceFeatures2' in extends) or ('VkPhysicalDeviceFeatures2KHR' in extends):
                    stype = t.find('member').attrib['values']
                    if name not in type_aliases:
                        pNextLUT.append((stype, name))
                        feature_structs[name] = stype

    print('#pragma once')
    print('// Autogenerated from extract_vulkan_extensions_sifter.py')

    print('static const struct {')
    print('\tVkStructureType sType;')
    print('\tsize_t size;')
    print('} pNextLUT[] = {')
    for entry in pNextLUT:
        print('\t{', entry[0], ',', f'sizeof({name})', '},')
    print('};\n')

    print('struct ExtensionRequirements {')
    print('\tvoid *primary_feature;')
    print('\tvoid *secondary_feature;')
    print('\tconst char * const *extension_dependencies;')
    print('\tuint32_t num_extension_dependencies;')
    print('\tuint32_t minimum_api_version;')
    print('};\n')

    member_names = []
    print('struct ExistingFeatureStructs {')
    for feat in feature_structs:
        print(f'\t{feat} {feat[16:]} =', '{', feature_structs[feat], '};')
        member_names.append(feat[16:])

    info_impl = []

    for ext in root.find('extensions').iter('extension'):
        if ('vulkan' in ext.attrib['supported'].split(',')) and (ext.attrib['type'] == 'device'):
            ext_name = ext.attrib['name']
            deps = ext.attrib['depends'] if 'depends' in ext.attrib else None

            if 'ANDROID' in ext_name:
                continue
            if 'AMDX' in ext_name:
                continue

            core_dep = 'VK_VERSION_1_0'
            ext_deps = []

            # Crude parsing. Don't want to implement basic grammar here, so just do
            # the minimal hackery needed to parse the xml.
            if deps:
                or_deps = deps.split(',')
                and_deps = deps.split('+')

                has_core_dep = False
                if len(or_deps) > 1:
                    for dep in or_deps:
                        if ('VK_VERSION' in dep) and ('+' not in dep) and ('(' not in dep) and (')' not in dep):
                            if dep > core_dep:
                                core_dep = dep
                                has_core_dep = True

                if not has_core_dep:
                    for dep in and_deps:
                        while dep[0] == '(':
                            dep = dep[1:]
                        while dep[-1] == ')':
                            dep = dep[:-1]
                        or_deps = dep.split(',')
                        has_core_dep = False
                        for subdep in or_deps:
                            if 'VK_VERSION' in subdep:
                                if subdep > core_dep:
                                    core_dep = subdep
                                    has_core_dep = True
                                break
                        if not has_core_dep:
                            ext_deps.append(subdep)

            features = []
            for reqs in ext.iter('require'):
                for t in reqs.iter('type'):
                    type_name = t.attrib['name']
                    type_name = type_aliases.get(type_name, type_name)
                    if (type_name in feature_structs) and (type_name not in features):
                        features.append(type_name)

            info_impl.append(f'if (ext == "{ext_name}")' + ' {')
            info_impl.append('\tdep = {};')
            info_impl.append(f'\tdep.minimum_api_version = {core_dep};')
            if len(ext_deps) != 0:
                info_impl.append('\tstatic const char * const exts[] = { ' + ', '.join([f'"{e}"' for e in ext_deps]) + ' };')
                info_impl.append('\tdep.num_extension_dependencies = uint32_t(sizeof(exts) / sizeof(exts[0]));')
                info_impl.append('\tdep.extension_dependencies = exts;')
            if len(features) >= 1:
                info_impl.append(f'\tdep.primary_feature = &{features[0][16:]};')
            if len(features) >= 2:
                info_impl.append(f'\tdep.secondary_feature = &{features[1][16:]};')
            info_impl.append('\treturn true;')
            info_impl.append('}')
            info_impl.append('')

            assert len(features) <= 2, 'Number of feature structs per extension is expected to be max 2.'

    print('\tvoid reset_pnext() {')
    for member_name in member_names:
        print(f'\t\t{member_name}.pNext = nullptr;')
    print('\t}\n')

    print('\tbool get_extension_requirements(ExtensionRequirements &dep) {')
    for l in info_impl:
        if len(l):
            print('\t\t' + l)
        else:
            print('')
    print('\t\treturn false;')
    print('\t}')

    print('};\n')

if __name__ == '__main__':
    main()

